# GitHub PR Auto-labeler Configuration

# API related changes
api:
  - 'src/**/*api*'
  - 'tests/api/**/*'
  - '**/test_*api*.py'

# UI/Frontend related changes
ui:
  - 'src/**/*ui*'
  - 'tests/ui/**/*'
  - '**/test_*ui*.py'
  - '**/test_*website*.py'

# Testing related changes
testing:
  - 'tests/**/*'
  - 'conftest.py'
  - 'pytest.ini'
  - '**/test_*.py'
  - '**/*_test.py'

# Documentation changes
documentation:
  - '*.md'
  - 'docs/**/*'
  - '**/*.rst'
  - '**/*.txt'
  - '.github/**/*.md'

# Configuration changes
configuration:
  - '*.toml'
  - '*.yml'
  - '*.yaml'
  - '*.json'
  - '*.cfg'
  - '*.ini'
  - 'Dockerfile*'
  - 'docker-compose*.yml'
  - '.env*'

# CI/CD related changes
ci-cd:
  - '.github/workflows/**/*'
  - 'scripts/**/*'
  - 'Makefile'
  - '.github/**/*'

# Dependencies
dependencies:
  - 'requirements*.txt'
  - 'pyproject.toml'
  - 'setup.py'
  - 'setup.cfg'

# Docker related
docker:
  - 'Dockerfile*'
  - 'docker-compose*.yml'
  - '.dockerignore'

# Security related
security:
  - '**/*security*'
  - '**/*auth*'
  - 'SECURITY.md'
  - '.github/workflows/security.yml'

# Performance related
performance:
  - '**/*performance*'
  - '**/*perf*'
  - 'tests/**/*slow*'

# Examples and utilities
examples:
  - 'examples/**/*'
  - 'utils/**/*'
  - 'scripts/**/*'

# Source code changes
source:
  - 'src/**/*'

# Bug fixes (based on branch or PR title patterns)
bug:
  - head-branch: ['^fix/', '^hotfix/', '^bugfix/']

# Features (based on branch or PR title patterns)
feature:
  - head-branch: ['^feat/', '^feature/']

# Chores (based on branch or PR title patterns)  
chore:
  - head-branch: ['^chore/', '^maintenance/']

# Refactoring (based on branch or PR title patterns)
refactor:
  - head-branch: ['^refactor/', '^refact/']